<script lang="ts">
  import { onMount, getContext, createEventDispatcher, onDestroy } from 'svelte';
  import { artifactCode, chatId, settings, showArtifacts, showControls } from '$lib/stores';
  import { artifactStore, artifactUIState, artifactActions } from '$lib/stores/artifacts/artifact-store';
  import { artifactIntegration } from '$lib/utils/artifacts/integration';
  import { createMessagesList } from '$lib/utils';
  import ArtifactPanel from '$lib/components/artifacts/ArtifactPanel.svelte';

  const i18n = getContext('i18n');
  const dispatch = createEventDispatcher();

  export let overlay = false;
  export let history;

  let messages = [];
  let unsubscribe: (() => void) | null = null;

  // Process messages and detect artifacts when history changes
  $: if (history) {
    messages = createMessagesList(history, history.currentId);
    processMessages();
  } else {
    messages = [];
    artifactStore.clearArtifacts();
  }

  // Process messages for PAS 3.0 artifacts
  const processMessages = () => {
    if (!messages?.length) {
      return;
    }

    // Clear existing artifacts
    artifactStore.clearArtifacts();

    // Process each assistant message for artifacts
    messages.forEach((message, messageIndex) => {
      if (message?.role !== 'user' && message?.content) {
        const artifacts = artifactIntegration.processResponse(
          message.content,
          message.id || `msg_${messageIndex}`
        );

        // Add artifacts to the store
        artifacts.forEach(artifact => {
          artifactStore.addArtifact(artifact);
        });
      }
    });

    // Show artifact panel if artifacts were found
    const currentArtifacts = $artifactStore;
    if (currentArtifacts.length > 0) {
      artifactActions.showPanel();
      // Select the most recent artifact
      const latestArtifact = currentArtifacts[currentArtifacts.length - 1];
      artifactActions.selectArtifact(latestArtifact.id);
    }
  };

  // Subscribe to artifact store changes to sync with OpenWebUI's showArtifacts
  onMount(() => {
    unsubscribe = artifactUIState.subscribe((state) => {
      if (state.isVisible !== $showArtifacts) {
        showArtifacts.set(state.isVisible);
      }
    });

    // Also sync the other direction
    const showArtifactsUnsubscribe = showArtifacts.subscribe((visible) => {
      if (visible !== $artifactUIState.isVisible) {
        if (visible) { artifactActions.showPanel(); } else { artifactActions.hidePanel(); }
      }
    });

    return () => {
      showArtifactsUnsubscribe();
    };
  });

  onDestroy(() => {
    if (unsubscribe) {
      unsubscribe();
    }
  });

  // Handle close event from artifact panel
  const handleClose = () => {
    showArtifacts.set(false);
    artifactActions.hidePanel();
    dispatch('close');
  };

  // Handle artifact selection changes
  const handleArtifactChange = (event) => {
    const { artifactId } = event.detail;
    artifactActions.selectArtifact(artifactId);
  };
</script>

<div 
  class="artifact-container h-full w-full {overlay ? 'overlay-mode' : ''}"
  class:visible={$showArtifacts}
>
  {#if $showArtifacts && $artifactStore.length > 0}
    <ArtifactPanel 
      on:close={handleClose}
      on:artifact-change={handleArtifactChange}
    />
  {:else if $showArtifacts}
    <!-- Fallback UI when no artifacts are detected -->
    <div class="flex items-center justify-center h-full text-gray-500 dark:text-gray-400">
      <div class="text-center">
        <div class="text-lg font-medium mb-2">
          {$i18n?.t('No artifacts found') ?? 'No artifacts found'}
        </div>
        <div class="text-sm">
          {$i18n?.t('Artifacts will appear here when generated by the AI') ?? 'Artifacts will appear here when generated by the AI'}
        </div>
      </div>
    </div>
  {/if}
</div>

<style>
  .artifact-container {
    transition: all 0.2s ease-in-out;
  }

  .artifact-container:not(.visible) {
    opacity: 0;
    pointer-events: none;
  }

  .artifact-container.visible {
    opacity: 1;
    pointer-events: auto;
  }

  .overlay-mode {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    z-index: 50;
    background: rgba(0, 0, 0, 0.1);
    backdrop-filter: blur(2px);
  }
</style>
